
version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
    - '3306:3306'
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: app
       MYSQL_USER: app
       MYSQL_PASSWORD: 9mREsvXDs9Gk89Ef

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef




